# -*- coding: utf-8 -*-
"""Yolov7_FishDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdtNiVAYNtZTfqFFgyJWqRfNh4FVgaWR
"""

# Commented out IPython magic to ensure Python compatibility.
# Download YOLOv7 repository and install requirements
!git clone https://github.com/WongKinYiu/yolov7
# %cd yolov7
!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# download COCO starting checkpoint
# %cd /content/yolov7
!wget "https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt"

# Commented out IPython magic to ensure Python compatibility.
data_loc="/content/drive/MyDrive/Fish_detection"
# %cat {data_loc}/data.yaml

!cp -r /content/drive/MyDrive/Fish_detection/valid /content/.

!cp -r /content/drive/MyDrive/Fish_detection/train /content/.

!rm /content/train/labels/vid7_frame*.txt
!rm /content/train/images/vid7_frame*.jpg
!rm /content/valid/labels_full/*
!rm /content/train/labels_full/*



# Commented out IPython magic to ensure Python compatibility.
# run this cell to begin training
# %cd /content/yolov7
!python train.py --batch 16 --cfg cfg/training/yolov7.yaml --epochs 55 --data {data_loc}/data.yaml --weights 'yolov7.pt' --device 0

!cp /content/yolov7/runs/train/exp/weights/best.pt /content/drive/MyDrive/Fish_detection/yolov7_weights/

!cp -r /content/drive/MyDrive/Fish_detection/test /content/.

!cp /content/drive/MyDrive/Fish_detection/yolov7_weights/best.pt /content/

# Commented out IPython magic to ensure Python compatibility.
#Example code from yolov5
# %cd /content/yolov7/
!python detect.py --weights /content/best.pt --img 416 --conf 0.4 --source /content/test/images > log_yolov7_short.txt

# Run evaluation
!python detect.py --weights /content/yolov7/runs/train/exp/weights/best.pt --conf 0.1 --source /content/test/images

#display inference on ALL test images

import glob
from IPython.display import Image, display

i = 0
limit = 10000 # max images to print
for imageName in glob.glob('/content/yolov7/runs/detect/exp/*.jpg'): #assuming JPG
    if i < limit:
      display(Image(filename=imageName))
      print("\n")
    i = i + 1

